
name: Deploy Looking Glass
on:
  push:
    branches:
      - main
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: pip install black
      - name: Formatting check
        run: black --check .

  deploy-dev:
    environment: dev
    env:
      STAGE: dev
      BUCKET_NAME: ${{ secrets.WAREHOUSE_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ./requirements.zip
          key: ${{ hashFiles('**/requirements.txt') }}
      - name: Install Requirements
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          make -B requirements
      - name: Build
        run: |
          make -B build
      - name: Upload to S3
        run: |
          make -B upload
      - name: Deploy
        run: |
          make -B deploy
  deploy-prod:
    needs: [deploy-dev]
    environment: prod
    env:
      STAGE: prod
      BUCKET_NAME: ${{ secrets.WAREHOUSE_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ./requirements.zip
          key: ${{ hashFiles('**/requirements.txt') }}
      - name: Install Requirements
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          make -B requirements
      - name: Build
        run: |
          make -B build
      - name: Upload to S3
        run: |
          make -B upload
      - name: Deploy
        run: |
          make -B deploy
